import type { Metadata } from 'next';
import '../globals.scss';
import StoreProvider from '@/components/StoreProvider';
import Header from '@/components/Header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Header />

          <div className="page">
            <main className="main">{children}</main>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
