import type { Metadata } from 'next';
import './globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      // {`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      className=""
    >
      {/* min-h-full flex flex-col */}
      <body className="">{children}</body>
    </html>
  );
}
